# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170312_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
