# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170312_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
