# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170312_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoggedInUser',
            new_name='Profile',
        ),
    ]
