# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170315_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadthread',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
