# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170317_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/avatars/no-avatar.svg', upload_to='avatars/'),
        ),
    ]
