# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170317_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/no-avatar.png', upload_to='avatars/'),
        ),
    ]
