# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:09
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth import get_user_model

from core.models import Profile

User = get_user_model()


class Migration(migrations.Migration):
    def add_chatbot_user(apps, schema_editor):
        user = User(username="chatbot", email="petryk.pjatochkin@gmail.com")
        user.save()
        profile, _ = Profile.objects.get_or_create(user=user)

    dependencies = [
        ('core', '0017_auto_20171129_1330'),
    ]

    operations = [
        migrations.RunPython(add_chatbot_user),
    ]
