# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170522_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
