# Generated by Django 2.0 on 2017-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171115_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('uk', 'Ukrainian'), ('it', 'Italian'), ('fr', 'French'), ('ru', 'Russian')], default='en', max_length=2),
        ),
    ]
