# Generated by Django 2.0 on 2017-12-14 17:49

import langid

from django.conf import settings
from django.db import migrations


def set_lang(apps, schema_editor):
    langid.set_languages([code for code, _ in settings.LANGUAGES])

    for row in apps.get_model('core', 'Message').objects.all():
        row.lang, _ = langid.classify(row.text)
        row.save(update_fields=['lang'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_message_lang'),
    ]

    operations = [
        migrations.RunPython(set_lang, reverse_code=migrations.RunPython.noop),
    ]
